"""
Django settings for hk project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import certifi
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=x3w#%uc*202m4!-^1i9u1v185s9b(((lho=^o2qn26q8q6_0_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hkfind'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'hk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""
"""
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'lasuoerbase',
    }
}"""


"""DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'myFirstDatabase',
            'ENFORCE_SCHEMA': False,
            'CLIENT': {
                'host': "mongodb+srv://support:onqx7jk5j8tGzYNx@cluster0.trqu4.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
,                #'port': port_number,
                #'username': 'db-username',
                #'password': 'password',
                #'authSource': 'db-name',
                #'authMechanism': 'SCRAM-SHA-1'
            },
            
        }}
"""
"""DATABASES = {
        'default': {
        'ENGINE': 'djongo',
        'NAME': 'myFirstDatabase',
        'HOST': "mongodb+srv://support:onqx7jk5j8tGzYNx@cluster0.trqu4.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
        'USER': 'support',
        'PASSWORD': 'onqx7jk5j8tGzYNx',
        'authMechanism': 'SCRAM'
    }
}    """  

"""

DATABASES = {
        'default': {
        'ENGINE': 'djongo',
        'NAME': 'dbtest',
        'HOST': "mongodb://alvarogonz:3479654@cluster3479-shard-00-00.r5klk.mongodb.net:27017,cluster3479-shard-00-01.r5klk.mongodb.net:27017,cluster3479-shard-00-02.r5klk.mongodb.net:27017/dbtest?ssl=true&replicaSet=atlas-ts4xhm-shard-0&authSource=admin&retryWrites=true&w=majority",
        'USER': 'alvarogonz',
        'PASSWORD': '3479654',
        'authMechanism': 'SCRAM'
           
    }
} """   
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS= [
    os.path.join(BASE_DIR,'static/')
]

STATICFILES_ROOT= os.path.join(BASE_DIR,'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_STORAGE="whitenoise.storage.CompressedManifestStaticFilesStorage"
