# Generated by Django 3.2 on 2021-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkfind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Procesarcompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxid', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('consumable', models.CharField(max_length=200)),
                ('token_amount', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
